# Data Ingestion

In [2]:
# Download adworks-bike-purchases.csv from GitHub. This file has 9132 rows.
import os
import urllib

basedataurl = "https://raw.githubusercontent.com/DataSnowman/MLonBigData/master/BikeBuyer/LoyaltyCardBuyers"
datafile1 = "adworks-bike-purchases.csv"
datafile_dbfs = os.path.join("/dbfs", datafile1)

if os.path.isfile(datafile_dbfs):
    print("found {} at {}".format(datafile1, datafile_dbfs))
else:
    print("downloading {} to {}".format(datafile1, datafile_dbfs))
    urllib.request.urlretrieve(os.path.join(basedataurl, datafile1), datafile_dbfs)

In [3]:
# Download potential-bike-buyers.csv from GitHub. This file has 18484 rows.
import os
import urllib

basedataurl = "https://raw.githubusercontent.com/DataSnowman/MLonBigData/master/BikeBuyer/LoyaltyCardBuyers"
datafile2 = "potential-bike-buyers.csv"
datafile_dbfs = os.path.join("/dbfs", datafile2)

if os.path.isfile(datafile_dbfs):
    print("found {} at {}".format(datafile2, datafile_dbfs))
else:
    print("downloading {} to {}".format(datafile2, datafile_dbfs))
    urllib.request.urlretrieve(os.path.join(basedataurl, datafile2), datafile_dbfs)

In [4]:
%sh
ls /dbfs/*.csv

In [5]:
# Create a Spark dataframe out of the adworks-bike-purchases.csv file.
data_purchases_all = sqlContext.read.format('csv').options(header='true', inferSchema='true', ignoreLeadingWhiteSpace='true', ignoreTrailingWhiteSpace='true').load(datafile1)
print("({}, {})".format(data_all.count(), len(data_all.columns)))
data_purchases_all.printSchema()

In [6]:
# Create a Spark dataframe out of the potential-bike-buyers.csv file.
data_potential_all = sqlContext.read.format('csv').options(header='true', inferSchema='true', ignoreLeadingWhiteSpace='true', ignoreTrailingWhiteSpace='true').load(datafile2)
print("({}, {})".format(data_potential_all.count(), len(data_potential_all.columns)))
data_potential_all.printSchema()

In [7]:
data_purchases_all.head(5)

In [8]:
data_potential_all.head(5)

In [9]:
display(data_purchases_all.limit(5))

LoyaltyCardID,Region,Age,Bikes
11417,Europe,68,7
11241,Europe,44,7
11420,Europe,66,7
11242,Europe,55,7
11429,Europe,60,6

In [10]:
display(data_potential_all.limit(5))

LoyaltyCardID,Region,FirstName,MiddleName,LastName,BirthDate,MaritalStatus,Gender,EmailAddress,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
11000,Australia,Jon,V,Yang,1971-10-06T00:00:00.000+0000,M,M,jon24@adventure-works.com,90000.0,2,0,Bachelors,Professional,1,0,3761 N. 14th St,NULL,1 (11) 500 555-0162,2011-01-19T00:00:00.000+0000,1-2 Miles
11001,Australia,Eugene,L,Huang,1976-05-10T00:00:00.000+0000,S,M,eugene10@adventure-works.com,60000.0,3,3,Bachelors,Professional,0,1,2243 W St.,NULL,1 (11) 500 555-0110,2011-01-15T00:00:00.000+0000,0-1 Miles
11002,Australia,Ruben,NULL,Torres,1971-02-09T00:00:00.000+0000,M,M,ruben35@adventure-works.com,60000.0,3,3,Bachelors,Professional,1,1,5844 Linden Land,NULL,1 (11) 500 555-0184,2011-01-07T00:00:00.000+0000,2-5 Miles
11003,Australia,Christy,NULL,Zhu,1973-08-14T00:00:00.000+0000,S,F,christy12@adventure-works.com,70000.0,0,0,Bachelors,Professional,0,1,1825 Village Pl.,NULL,1 (11) 500 555-0162,2010-12-29T00:00:00.000+0000,5-10 Miles
11004,Australia,Elizabeth,NULL,Johnson,1979-08-05T00:00:00.000+0000,S,F,elizabeth5@adventure-works.com,80000.0,5,5,Bachelors,Professional,1,4,7553 Harness Circle,NULL,1 (11) 500 555-0131,2011-01-23T00:00:00.000+0000,1-2 Miles

# Data Preparation